name: Lint
on: push
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Installing Lint
        run: sudo make install-lint
      - name: Lint
        run: make lint
